# Generated by Django 2.0.7 on 2021-09-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComputersViewList',
            new_name='Computers',
        ),
    ]
