# Generated by Django 2.0.7 on 2021-09-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0002_auto_20210901_1016'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Computers',
            new_name='Computer',
        ),
    ]
